ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Contexto y Alcance


ifdef::arc42help[]
[role="arc42help"]
****
.Contenido  
El ámbito y contexto del sistema, como su nombre lo indica, delimita el sistema (es decir, su ámbito) de todos 
sus interlocutores (sistemas y usuarios vecinos, es decir, el contexto del sistema). De este modo, especifica las interfaces externas.

Si es necesario, diferencie el contexto empresarial (entradas y salidas específicas del dominio) del contexto técnico (canales, protocolos, hardware)..

.Motivación
Las interfaces de dominio y las interfaces técnicas con los socios de comunicación se encuentran entre los aspectos más críticos de su sistema. Asegúrese de comprenderlas por completo.

.Forma
Varias opciones:

* Varios diagramas de contexto
* Listas de socios de comunicación y sus interfaces.


.Más información

Vea https://docs.arc42.org/section-3/[Context and Scope] en la documentación arc42.

****
endif::arc42help[]

=== Contexto de Negocio

[plantuml,png]
----
  actor Usuario
  database Pod as "Base de Datos"
  Usuario --> (WIChat): Interactúa
  WIChat --> (Wikidata): Solicita datos
  Wikidata --> (WIChat): Devuelve imágenes y respuestas
  WIChat --> (LLM_API): Envía consultas
  LLM_API --> (WIChat): Devuelve respuestas
  Usuario --> (Pod): Inicia sesión y registra resultados de partida
----


[options="header",cols="1,2"]
|===
|Elemento|Descripción
| _Usuario_ | _El concursante que interactúa con la aplicación, juega y recibe pistas._
| _Base de Datos_ | _Sistema de almacenamiento que guarda información relevante sobre el usuario._
| _WIChat_ | _Aplicación web principal donde se desarrolla el juego._
| _Wikidata_ | _Fuente de donde se extraen las preguntas, las imágenes y las respuestas._
| _LLM_API_ | _API que integra un modelo de lenguaje que se utiliza para generar pistas dinámicas y conversacionales que ayudan al concursante a responder las preguntas._
|===

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
Especificación de todos los interlocutores (usuarios, sistemas informáticos, etc.) con explicaciones de las entradas y salidas o interfaces específicas del dominio. 
Opcionalmente, puede añadir formatos o protocolos de comunicación específicos del dominio.

.Motivación
Todas las partes interesadas deben comprender qué datos se intercambian con el entorno del sistema.

.Forma
Todo tipo de diagramas que muestran el sistema como una caja negra y especifican las interfaces del dominio con los socios de comunicación.

Como alternativa (o adicionalmente), puede utilizar una tabla. 
El título de la tabla es el nombre de su sistema, las tres columnas contienen el nombre del interlocutor, las entradas y las salidas.

****
endif::arc42help[]



**<optionally: Explanation of external domain interfaces>**

=== Technical Context

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
endif::arc42help[]

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
